### ISSUE TITLE
PrimeReact-with Hooks

### ISSUE THREAD

**Issue by Abubakr7** [primefaces/primereact#1715]
When you are migrated to hooks? 
It's very important. MUI has hooks components.
If you want to outstrip Material UI you must migrate to hooks. 
I hope you read this and started to act. 
Good luck!

**Comment by mertsincan** [comment]
Hi,

Thanks a lot for your interest. All of our demo pages have hooks and TS demos in codesandbox. I'm just trying to update the documentation with Hooks instead of Class component. I'll finish this asap.
<img width="1469" alt="Screen Shot 2020-12-15 at 09 22 54" src="https://user-images.githubusercontent.com/11868120/102179084-9bdfba00-3eb7-11eb-9200-022ddd4407f1.png">

Best Regards,
