### ISSUE TITLE
Primereact breadcrumb:: page refresh issue on click of breadcrumb

### ISSUE THREAD

**Issue by Nirav4Stridely** [primefaces/primereact#1735]
We are using prime react breadcrumb control in our react js project. when we click on breadcrumb, page is getting refresh.

Page with prime react breadcrumb control
![breadcrumb](https://user-images.githubusercontent.com/76509793/102974595-cf0ff200-4524-11eb-8573-5263d164e06b.png)
 
While click on dashboard breadcrumb, page is getting load and redirect to dashboard.
![breadcrumb click](https://user-images.githubusercontent.com/76509793/102974702-fbc40980-4524-11eb-8dd9-a6cede410208.png)

**Comment by mertsincan** [comment]
Hi,

Do you get an error on console?

**Comment by Nirav4Stridely** [comment]
Hello,
No, i do not get any error in console.

**Comment by mertsincan** [comment]
Hi,

This is very interesting. Could you please check the breadcrumb icons in the inspector of browser? Also, is there any place I can test this? Maybe, you can create a sample project for us to replicate.

Best Regards,

**Comment by mertsincan** [comment]
Also, please check import 'primeicons/primeicons.css'; in your pages or global page.

**Comment by Nirav4Stridely** [comment]
Hello,

Here, I have attached sample project for you to replicate the issue.

**Sample project:** [ReactDemo.zip](https://github.com/primefaces/primereact/files/5899967/ReactDemo.zip)

**Comment by melloware** [comment]
I can't reproduce either.  Please create a Code Sandbox reproducer.

**Comment by melloware** [comment]
Please create a code sandbox reproducer showing the problem. You can use this starter: https://codesandbox.io/s/primereact-test-forked-bbns8k

**Comment by kcs-vishnumahindalekar** [comment]
> We are using prime react breadcrumb control in our react js project. when we click on breadcrumb, page is getting refresh.
> 
> Page with prime react breadcrumb control ![breadcrumb](https://user-images.githubusercontent.com/76509793/102974595-cf0ff200-4524-11eb-8573-5263d164e06b.png)
> 
> While click on dashboard breadcrumb, page is getting load and redirect to dashboard. ![breadcrumb click](https://user-images.githubusercontent.com/76509793/102974702-fbc40980-4524-11eb-8dd9-a6cede410208.png)

Hello did you get solution on that

**Comment by melloware** [comment]
I am still waiting for someone to create a Code Sandbox showing me the issue...

**Comment by stefrado** [comment]
Hi all.

I encountered the same issue. When i click on a breadcrumb with the attribute `url` on it the page will reload and redirects to the page from the URL. This is not the expected behaviour if you expect that the page will not reload and just redirect to the link. In the sandbox if you click on the home icon or on foo the page will reload. This is the behaviour described in this issue. 

[The issue is visible in this snippet](https://codesandbox.io/s/primereact-test-forked-4l92mn)

https://github.com/primefaces/primereact/assets/109965488/d17791ce-b417-4fed-a23e-9388e91d4bb6

> In this video you'll see the issue if you click on `foo` and the expected behaviour when you click on `bar`

I have found a solution to this problem. Inside the model breadcrumb attribute there is a property called `command`, with this property i have made a function using `react-router-dom`, that with redirect but not reload.

> In the demo i have implemented this if you click on `bar`. 

If you want this to work, you'll need to use react-browser-router (very handy to make a client router). If you have done this inside the file where you want the breadcrumbs you'll need to add the function `useNavigate` from `react-router-dom`.

It will look something like this

```js
import {useNavigate} from 'react-router-dom';

const Header = () => {
const navigate = useNavigate()
}
```
Then you will need to add this navigate to the command property of the breadcrumb, this will look something like this.

```js
<BreadCrumb
        className="border-noround border-none border-bottom-1 shadow-1 surface-card"
        home={{ icon: 'pi pi-home', command: () => navigate('/') }}
        model={[
          { label: 'Foo', command: () => navigate('/foo') },
          { label: 'Bar', command: () => navigate('/bar') },
        ]}
      />
```

> Make sure you are using the router of `react-router-dom`, otherwise this would not work.

This is a work around the problem that i think is very clear. The site reloads after clicking on a link. Using browser router the issue is resolved, but its dependent on other modules.

I hope this explains the issue, and will help all of you

**Comment by melloware** [comment]
I still don't understand. React Router DOM has nothing to do with Breadcrumb right?  Breadcrumb are just Menu option links to do whatever you want?

**Comment by bloodykheeng** [comment]
here is the solution
  <BreadCrumb
                model={items}
                home={{
                    label: "Home",
                    icon: "pi pi-home",
                    command: (e) => {
                        e.originalEvent.preventDefault();
                        navigate("/");
                    },
                }}
            />  

just use this and prevent default command: (e) => {
                        e.originalEvent.preventDefault();
                        navigate("/");
                    },

**Comment by thinhhoang123** [comment]
> here is the solution <BreadCrumb model={items} home={{ label: "Home", icon: "pi pi-home", command: (e) => { e.originalEvent.preventDefault(); navigate("/"); }, }} />
> 
> just use this and prevent default command: (e) => { e.originalEvent.preventDefault(); navigate("/"); },

Thanks, it's work well
