### ISSUE TITLE
Update to Chart.js 3.3.2

### ISSUE THREAD

**Issue by NathanPB** [primefaces/primereact#1802]
**I'm submitting a ...**  (check one with "x")
```
[ ] bug report
[ ? ] feature request
[ ] support request => Please do not submit support request here, instead see https://forum.primefaces.org/viewforum.php?f=57
```
ChartJS 3 is currently in beta, any plans to update the current PrimeReact ChartJS wrapper? I'd like to dig into that and do some work to help the update

**Comment by mertsincan** [comment]
Hi @NathanPB,

Can you make these changes after Chart Js released? There may be differences between beta and major releases in our theme.

**Comment by NathanPB** [comment]
> Hi @NathanPB,
> 
> Can you make these changes after Chart Js released? There may be differences between beta and major releases in our theme.

Sure, I'll wait for the release

**Comment by mertsincan** [comment]
Thanks a lot, @NathanPB ;) I'll wait for your PR :D

**Comment by dnairns-arch** [comment]
I am using PrimeReact and would like to see this as one of the updates and features once they release. I have to rewrite around 100+ components to get the functionalities of ChartJS 3, due to a project requirement for horizontal stacked bar charts. I tried upgrading to beta, and had a handful of issues so i ended up writing my own chart component for the HZ Stacked Bar. The line graphs seem to work okay with the default chart class in PrimeReact just FYI.

If you guys could add the ChartJS 3.0 to the feature list when they drop the first release I would greatly appreciate it!

**Comment by mertsincan** [comment]
Thanks @dnairns-arch, I'll work on it for 6.4.0.

Best Regards,

**Comment by dattebayorob** [comment]
Break change @mertsincan ?

**Comment by mertsincan** [comment]
Yes, @dattebayorob ;)
