### ISSUE TITLE
Multiselect malfunction with 'optionValue' prop setted

### ISSUE THREAD

**Issue by giovannispd** [primefaces/primereact#1897]
[X ] bug report
[ ] feature request
[ ] support request

in multiselect, when 'optionValue' prop is set, the item selection don't work!

* **React version:**
16.13.1

* **PrimeReact version:**
6.2.1

* **Browser:** [Chrome 89 ]

 
* **Language:** [ ES6/7 | ES5 ]

**Comment by on2air** [comment]
I can confirm this. Seeing same bug.
I found a workaround in the meantime until its fixed:
change `optionValue="id"`
to `optionValue={ option => typeof option === 'object' ? option['id'] : option`

The bug is in the isSelected() function where it checks whether each value is in the array of selected items, but since its no longer an object because of using optionValue, it returns null everytime.  With this workaround it will work in both scenarios - if the option is the full object like normal, or if its just the id value.

**Comment by vrinceanuv** [comment]
I can confirm. Example here:
https://codesandbox.io/s/multi-select-optiovalue-bug-0ef66
