### ISSUE TITLE
Lost Filled effect on dialog after upgrade to primereact 6.3.0

### ISSUE THREAD

**Issue by deaa1111** [primefaces/primereact#2023]
**I'm submitting a ...**  (check one with "x")
```
[x] bug report
[ ] feature request
[ ] support request => Please do not submit support request here, instead see https://forum.primefaces.org/viewforum.php?f=57
```

**Current behavior**
Im using Ultaima Template
Lost Filled effect on dialog inputs after upgrade to primereact 6.3.0 after upgrade from 6.0.1 to 6.3.0

* **React version:**
17.0.2

* **PrimeReact version:**
6.3.0

**Comment by mertsincan** [comment]
Hi,

In all Prime* libraries, almost all users wanted the appendTo={document.body} by default. That's why we set it as default in all of them. Details; https://github.com/primefaces/primereact/issues/1875

We'll need to make a change related to this in the templates. For now, please use;
```
PrimeReact.appendTo = 'self'

OR

useEffect(() => { // mounted
    PrimeReact.appendTo = document.getElementsByClassName('layout-wrapper')[0];
}, []);
```
Best Regards,
