### ISSUE TITLE
DataTable multiple selection with metakey doesn't work with checkbox column

### ISSUE THREAD

**Issue by AuthorProxy** [primefaces/primereact#2065]
I updated from "primereact": "^6.1.0", to "primereact": "^6.3.2",

Before I had a table with `selectionMode="multiple"` and metaKey, and columns with `<Column selectionMode="multiple" />` and it worked like this:

When I click on checkboxes - it selects multiple rows
When I click a rows without shift key - it selects only a single row and a checkbox in that row

In new version I tried different setups and cannot figure a way how to achieve this, looks like there no way now to do this.
When I set `selectionMode="multiple"` and metaKey - it works as expected with shift key, but when I add checkbox column `<Column selectionMode="multiple" />` - it disable metakey and clicking on the rows always select multiple items.

Expected behaviour checkbox column and metakey options that is worked on "primereact": "^6.1.0":
Not holding shift or ctrl:
When clicking on a row outside of the checkbox, single row should be selected and single checkbox should be checked
When clicking on the checkboxes, multiple rows should be selected

Can you confirm a bug or give a solution?

**Comment by AuthorProxy** [comment]
Can you confirm @mertsincan ?

**Comment by mertsincan** [comment]
Hi @AuthorProxy,

This is by design. But, you can do this using onRowSelect callback. Please try;
https://codesandbox.io/s/stoic-feather-x8yb1?file=/src/demo/DataTableSelectionDemo.js

Best Regards,

**Comment by AuthorProxy** [comment]
@mertsincan can you add type: "checkbox" | "row" to `onSelect` handler, the same as it impletemnted on the `onRowSelect` handler

**Comment by AuthorProxy** [comment]
@mertsincan also e.type doesn't show `TD around checkbox` as `checkbox type`, so... it's not easy to implement this with current `by design`

**Comment by mertsincan** [comment]
Hi @AuthorProxy,
Sorry for the typo! :( Please use onRowSelect instead of onSelect in the above sample.
https://codesandbox.io/s/stoic-feather-x8yb1?file=/src/demo/DataTableSelectionDemo.js

1.  Done! Please use onRowSelect callback. type DataTableSelectType = 'row' | 'cell' | 'checkbox' | 'radio' | 'all';
2. and 3. Added onAllRowsSelect and onAllRowsUnselect callbacks to DataTable; https://github.com/primefaces/primereact/issues/2093
4. Unfortunately, I didn't understand this problem.
5. Done! Good catch!
6. Checkbox selection doesn't support cell selection mode. Therefore, onCellSelect-onCellUnselect will never be called.

Thanks a lot for the feedback!

**Comment by AuthorProxy** [comment]
@mertsincan here is full working functionality, you can check how I implement it now, and maybe found some useful thoughts for future design: https://codesandbox.io/s/frosty-jang-bi4o8?file=/src/demo/DataTableSelectionDemo.js

4. just want to say that I cannot fully rely on the type="checkbox", because the space around the checkbox (inside current `td`) indicated as `tpye="row"`, but I am sure it should be `checkbox` too, if you implement custom selection logic, because it's not easy to point directly to the checkbox center
