### ISSUE TITLE
BundlePhobia: Missing entry point

### ISSUE THREAD

**Issue by melloware** [primefaces/primereact#2508]
Trying to get PrimeReact to report in BundlePhobia: https://bundlephobia.com/

It appears because PrimeReact does not have `  "main": "primereact.all.min.js",` in package.json it can't determine its entrypoint.

cc @blutorange for thoughts?

**Comment by blutorange** [comment]
Hmm, something like `require("primereact")` fails because there is no entry point. So the reason for not having a single entry point is because the intended usage is to import the individual components directly, right? Like `require("primereact/badge")`

So basically this package does not have a single entry point, but many individual entry points. The first thing that comes to my mind is that the `package.json` does allow specifying multiple entry point: https://nodejs.org/api/packages.html#subpath-exports

```json
{
  "exports": {
    "./badge": "./badge/badge.js",
    "./dialog": "./dialog/dialog.js"
  }
}
```

IDK if bundlephobia even supports this, might want to try that first. At any rate, this `exports` field does have implications: (a) consumers can only import from those entry points, everything else will result in a failure (although e.g. webpack might not enforce it); and (b) this should be considered a breaking change and increment the major version.

Also, I just noticed that there's a `package.json` in each component directory, like a monoreop. So an alternative would be to publish each module separately on NPM (`primereact/badge`, `primereact/dialog` etc.), which does reflect the intended usage better. But yeah, that would be quite a drastic change.

**Comment by melloware** [comment]
got it. that makes a lot of sense!  publishing each component separately seems like overkill and limiting exports to only what is in the package.json also seems limiting.  OK I am good with closing this ticket.

**Comment by blutorange** [comment]
Also, I just found this: https://github.com/pastelsky/bundlephobia/issues/379 It does not even support the `exports` field for now, so yeah, multiple packages would be only way...
