### ISSUE TITLE
New Component: Signature

### ISSUE THREAD

**Issue by cesarpachon** [primefaces/primereact#2524]
Hello, in primefaces there is a p:signature component that allows the user to create a "digital signature" by drawing in a canvas.
I wonder if there is a equivalent for primereact or what suggestion exist to implement a similar feature.
thanks!

**Comment by melloware** [comment]
PrimeFaces uses a very old Jquery component for signatures so that won't work for PrimeReact.  

Maybe building a new component around this: https://github.com/szimek/signature_pad

But styled and themes using PrimeTek theme.  There is a react component already but it wouldn't be themed with your PrimeTek theme: https://www.npmjs.com/package/react-signature-canvas
