### ISSUE TITLE
DataTable - Row Grouping: Expandable row groups that are expanded by default cannot be collapsed

### ISSUE THREAD

**Issue by pre-rendered** [primefaces/primereact#2598]
**I'm submitting a ...**
```
[x] bug report
[ ] feature request
[ ] support request
```

**Codesandbox Case (Bug Reports)**
https://codesandbox.io/s/trusting-khayyam-2dr5z

**Current behavior**
If all rows are set to be expanded by default, any group with more than one row in its group cannot be collapsed. The only grouped rows that can be collapsed are those with exactly 1 row in the group.

**Expected behavior**
All expandable row groups, regardless of how many rows are in its group, should be collapsible.
For what it's worth, this sandbox shows the expected behavior (expands all `Pronom personnel` groups by default, can collapse any of these groups); It uses version 4.2.2 of primereact, but downgrading is not an option for us:
https://codesandbox.io/s/primereact-datatable-issue-vb256?file=/src/index.js

**Minimal reproduction of the problem with instructions**
See codesandbox: https://codesandbox.io/s/trusting-khayyam-2dr5z
Click on any arrow to collapse the group.
Notice that the only group that can be collapsed is `Elwin Sharvill`'s group, which only has one row.

* **React version:**
17.0.1

* **PrimeReact version:**
7.2.0

**Comment by rsareth** [comment]
Hi,

I'm facing the same issue in the version 9.3.1.

**Comment by kbeeveer46** [comment]
I am waiting for a fix, as well. We use grouping with "expand all" buttons on many of our pages. Once someone clicks that button they are unable to collapse individual rows if the group has more than 1 row. And like the title says, if we expand all by default on page load, the same issue occurs.

**Comment by rsareth** [comment]
I've just upgraded to the version 9.4.0 and now it is working for me.

**Comment by melloware** [comment]
Hmmm I just tried his sandbox on 9.4.0 and its still not working: https://codesandbox.io/s/determined-panini-pfq7vd

@rsareth can you look and compare with what you are doing?

**Comment by rsareth** [comment]
You are right. I started a new project on my computer in js and I doesn't work. I don't understand why it is working on my TS project.

**Comment by rsareth** [comment]
@melloware I found the option you need to add: https://codesandbox.io/s/funny-zeh-3sle8f?file=/src/demo/DataTableRowGroupDemo.js

I don't know for now if it is the right solution, but just by initializing the dataKey with the same value as groupRowsBy, it is working.

**Comment by rsareth** [comment]
I am not an expert in JS so I tried to understand at least.

According to the presence or not of the dataKey in the property of the component DataTable, the type of data set in the variable **expandedRows** is an array of object or a map<int, object>.

So, in the file [TableBody.js:554 - onRowToggle](https://github.com/primefaces/primereact/blob/e3a768ed75605ed3c6ba0b13a3fc90c47728603f/components/lib/datatable/TableBody.js#L554), the logic is so weird if the main IF statement.

Just by reading those 2 lines, it should trigger something:
- [line 562](https://github.com/primefaces/primereact/blob/e3a768ed75605ed3c6ba0b13a3fc90c47728603f/components/lib/datatable/TableBody.js#L562)
```javascript
[...]

expandedRows = props.expandedRows ? { ...props.expandedRows } : {};

[...]
```
- [line 580](https://github.com/primefaces/primereact/blob/e3a768ed75605ed3c6ba0b13a3fc90c47728603f/components/lib/datatable/TableBody.js#LL580C17-L580C82)
```javascript
[...]

expandedRows = props.expandedRows ? [...props.expandedRows] : [];

[...]
```

Because at the end of the function, we have this:
```javascript
if (props.onRowToggle) {
    props.onRowToggle({
        data: expandedRows
    });
}
```

Don't you think it would be wise to preserve the same type of data in the logic for the variable **expandedRows**? For the working use case, it is a map (Object).

**Comment by melloware** [comment]
Let me investigate. I wonder if there was a reason they were different.

**Comment by melloware** [comment]
OK I agree with your analysis this is strange and the behavior is different with or without dataKey.  I am not sure the proper way to fix this.  I have added the label "workaround" as like you said setting `props.dataKey = props.groupRowsBy` seems to resolve this particular issue.

**Comment by rsareth** [comment]
BTW, I've made another test by adding a new column. Just look at this: https://codesandbox.io/s/compassionate-hill-9l28x6?file=/src/demo/DataTableRowGroupDemo.js

In the console, there is a lot of error:
```
Warning: Encountered two children with the same key, `unqualified`. Keys should be unique so that components maintain their identity across updates. Non-unique keys may cause children to be duplicated and/or omitted — the behavior is unsupported and could change in a future version.
    at tbody
```

I'm afraid that the fix could be complicated.

**Comment by melloware** [comment]
Ok thanks I definitey will try and fix that error only because any React warning like that is usually a bad sign of other problems!

**Comment by rsareth** [comment]
Thank you, @melloware

**Comment by melloware** [comment]
Ahhh OK the bug is deeper than just setting `dataKey = groupBy` as now the dataKey is meant to uniquely identify the row.  But now since `status` is the key for too many rows React throws the error about "non unique" keys.  I think the original issue is still the underlying issue with this whole feature.  

`dataKey` should always be unique to identify each row and NOT have to match the groupByRows.

**Comment by rsareth** [comment]
Ok, thank you @melloware for digging deeper. FYI, I am using the component DataTable with several features activated.

For now, I have to use the latest version with this important bug.

**Comment by melloware** [comment]
OK fixed the sandbox: https://codesandbox.io/p/sandbox/nostalgic-goodall-hlzrvw?file=%2Fsrc%2Fdemo%2FDataTableRowGroupDemo.js%3A39%2C21

The problem was with the way you were definining the `setExpandedRows` you need to only set it once for each `representative.name` you were setting it for EVERY customer.
