### ISSUE TITLE
Ultima theme: active menu with link is not selected on page refresh

### ISSUE THREAD

**Issue by RushPVA** [primefaces/primereact#286]
http://prntscr.com/i18d0g

**Comment by cagataycivici** [comment]
That should be because there is no relation between components link and the forms. It is not like components/forms. I think you can customize this behavior on your side with react-router apis. We'll see if we can at least color forms or implement this as built-in behavior. Since this tracker is for PrimeReact itself closing and we'll discuss this with @mertsincan and @Merve7
