### ISSUE TITLE
Checkbox and Radio should mark checked/onChange props as required

### ISSUE THREAD

**Issue by RushPVA** [primefaces/primereact#287]
Warning: Failed prop type: You provided a `checked` prop to a form field without an `onChange` handler. This will render a read-only field. If the field should be mutable use `defaultChecked`. Otherwise, set either `onChange` or `readOnly`.
    in input (created by Checkbox)
    in div (created by Checkbox)
    in div (created by Checkbox)
    in Checkbox (at Editor.js:103)
    in span (created by BodyCell)

**Comment by PWAlessi** [comment]
This issue still occurs in 1.4.1.
 My code:
                                <Checkbox
                                    inputId="cbDiscoverable"
                                    onChange={(e) => this.setState({discoverable: e.checked})}
                                    checked={this.state.discoverable}
                                    />

The error:
Warning: Failed prop type: You provided a `checked` prop to a form field without an `onChange` handler. This will render a read-only field. If the field should be mutable use `defaultChecked`. Otherwise, set either `onChange` or `readOnly`.
    in input (created by Checkbox)
    in div (created by Checkbox)
    in div (created by Checkbox)
    in Checkbox (at AddDataset.js:97)
