### ISSUE TITLE
MenuItem: command(e) Add custom parameters

### ISSUE THREAD

**Issue by MingRock** [primefaces/primereact#2960]
### Describe the feature you would like to see added

example:
MenuItem:   command(e,customParameters){}
Menu: menu.current.toggle(event,customParameters);
ContextMenu: contextMenu.current.show(e,customParameters)

### Reproducer

https://codesandbox.io/s/primereact-test-forked-x5w48t?file=/src/index.js

Be able to pass the menu custom data like the current ROW being selected etc.

**Comment by melloware** [comment]
Isn't this already fixed with this: https://github.com/primefaces/primereact/issues/2939

You can add whatever extra data you want in the `MenuItem` by adding to `data?: any` right?

**Comment by melloware** [comment]
cc @[manuelpoelzl](https://github.com/manuelpoelzl)

**Comment by manuelpoelzl** [comment]
Hi @MingRock 

I think this use case is covered with the issue mentioned above.

In the future you will be able to store any kind of information you want in the data property, @melloware  has already merged this new feature and it should be available in v8.2.0.

This property also eliminates the need for custom parameters in the command function, since you can access the current item and its properties with the event passed as a parameter.

For example, if you want to access the item's label in the command function, you can do so with: 
```js
{
    icon: "pi pi-plus-circle",
    label: "Add new",
    command: (e) => {

                /*e.item is the current item and here you can access all properties*/
                const itemLabel= e.item.label;

            }
    },
```
I have also created a small example showing this possibility:
https://codesandbox.io/s/primereact-test-forked-hzzxlm?file=/src/index.js

**Comment by MingRock** [comment]
@melloware 

look this demo


https://codesandbox.io/s/primereact-test-forked-x5w48t?file=/src/index.js

**Comment by melloware** [comment]
@MingRock so in this example you think it would be a useful feature. where you pass the menu some current context like what row you clicked on.

**Comment by mertsincan** [comment]
I agree with @melloware and @manuelpoelzl. The 'toggle' method is to show menu. If you give an extra parameter, we need to keep it in state or ref so that we can send this parameter in our command method. it will be the same as keeping this parameter in state in your app.
https://codesandbox.io/s/primereact-test-forked-46me6f?file=/src/index.js

Best Regards,
