### ISSUE TITLE
InputTextarea: expands but will not shrink

### ISSUE THREAD

**Issue by Toksisitee** [primefaces/primereact#3274]
### Describe the bug

The Inputtextarea component with a autoResize property keeps expanding in height as more text is typed, but will not shrink down after the text is removed. Instead, it will stay stuck at the current increased size. This seems to only happen when the component is given a style of ``border: 0px``. Tested and reproduced in both PrimeReact 8.4.0 and 8.5.0.

### Reproducer

https://codesandbox.io/s/proud-moon-z2mt38

### PrimeReact version

8.4.0

### React version

18.x

### Language

ALL

### Build / Runtime

Create React App (CRA)

**Comment by melloware** [comment]
Insane I fixed your example: https://codesandbox.io/s/lively-sun-ko1q0k

it turns out its not 0px that throws it off even if you do `border: 1px none` or `border: 1px hidden` it still fails because the "scrollHeight" calculation won't update.  Must be a browser glitch not a PrimeReact glitch.

Anyway to fix your scenario you have to do `border: "1px solid transparent"` basically leave the border there but make it the same color as the background so its invisible but still causes the DOM scrollheight to calculate.

**Comment by Toksisitee** [comment]
Thank you for the prompt response and workaround!
