### ISSUE TITLE
DataTable: TypeError when adding and starting editing a new row

### ISSUE THREAD

**Issue by kalinkrustev** [primefaces/primereact#3476]
### Describe the bug

When adding a new row and immediately setting it in edit mode, an error `Cannot read properties of undefined (reading 'data')` is thrown in [BodyCell EditorCallback](https://github.com/primefaces/primereact/blob/7eb90e0ba81d8e2b59b9b58b27c99eec4d389269/components/lib/datatable/BodyCell.js#L253). `EditingMeta` was not initialized in this specific case.

### Reproducer

https://codesandbox.io/s/primereact-test-forked-224zjd?file=/src/index.js

### PrimeReact version

8.6.1

### React version

18.x

### Language

ALL

### Build / Runtime

Create React App (CRA)

### Steps to reproduce the behavior

Use the reproducer URL, click to add a new row and start typing in one of the fields.

**Comment by melloware** [comment]
Were you going to submit a PR?

**Comment by kalinkrustev** [comment]
I was planning to, but haven't found a solution yet, as I had to handle other stuff first.

**Comment by kalinkrustev** [comment]
I was using some workaround for some time (i.e. several months), but recently I found the workaround does not work in all cases.

**Comment by yanxiyue** [comment]
1. The cause seems to be that editingMeta was not initialized in this specific case.
2. editingMeta will be updated by useUpdateEffect hook, when BodyCell's editingState changed.
3. in this case, BodyCell is not mounted yet, so, the update logic will not be executed.

Therefore，I try change useUpdateEffect to React.useEffect, it works well. see PR #3664
