### ISSUE TITLE
Ripple: ripple start point is not init in mobile env

### ISSUE THREAD

**Issue by Lanace** [primefaces/primereact#3526]
### Describe the bug

in mobile, ripple position is always top: 0px, left: 0px.
because onMouseDown params is not   MouseEvent in mobile
it's TouchDown event.

so use targetTouches pageX and pageY

```jsx
var offset = DomHandler.getOffset(targetRef.current);

var x =
  event.targetTouches[0].pageX -
  offset.left +
  document.body.scrollTop -
  DomHandler.getWidth(inkRef.current) / 2;
var y =
  event.targetTouches[0].pageY -
  offset.top +
  document.body.scrollLeft -
  DomHandler.getHeight(inkRef.current) / 2;
```

and i have one question...
why event prevent in onTouchStart?
i want scroll event, but touch start event prevented.

```jsx
var onTouchStart = function onTouchStart(event) {
  onMouseDown(event);
  // event.preventDefault();
};
```

### PrimeReact version

8.7.1-SNAPSHOT

### React version

18.x

### Language

TypeScript

### Build / Runtime

Vite

### Browser(s)

Chrome 106.0.5249.119

### Steps to reproduce the behavior

1. in mobile device, click button
2. ripple effect start incorrect position

### Expected behavior

ripple effect start on touched point

**Comment by Lanace** [comment]
cc @kkimdev

ref: https://github.com/primefaces/primereact/pull/3499

**Comment by melloware** [comment]
@Lanace the reason I use `event.preventDefault` is because of this: https://web.dev/mobile-touchandmouse/

The order of mouse events is this:

![image](https://user-images.githubusercontent.com/4399574/199004850-27338f86-eb8a-4e65-b433-f480abac2757.png)

So it would call `onMouseDown` after calling `onTouchStart` and I don't think you want that happening if TouchStart is fired you don't want to then fire again on `MouseDown`.

**Comment by melloware** [comment]
Can you review my PR.

**Comment by melloware** [comment]
OK I was able to handle `event.preventDefault` a different way.
