### ISSUE TITLE
ButtonSet: styling

### ISSUE THREAD

**Issue by airowe** [primefaces/primereact#3743]
### Describe the bug

Buttons in a `ButtonSet` do not seem to be customizable via css to allow for centering buttons that wrap to additional rows

<img width="188" alt="image" src="https://user-images.githubusercontent.com/52685/205759601-18584f0d-219a-4dbd-8492-4b850b0c9116.png">

### PrimeReact version

8.6.0

### React version

17.x

### Language

TypeScript

### Build / Runtime

Create React App (CRA)

### Expected behavior

Ideally, the buttons in additional rows could be styled to allow for flexbox-like styling (`justify-content:justify`) or something similar. I have been able to style the button's right border to ensure it shows when the buttons no longer have a right sibling, but can not update the alignment/positioning of the buttons within the parent `buttonset` component.

**Comment by melloware** [comment]
So just to be clear in the "Custom Content" screenshot above you want the button on the second row to be centered not left aligned?

**Comment by airowe** [comment]
Yes that's right sorry for being unclear

**Comment by melloware** [comment]
@airowe because `p-buttonset` is just CSS i don't think there is any way to change how you want with just CSS.  It would require manipulating the DOM but since ButtonSet is not a React Component I don't think this will be possible So you best bet might be just to take the `p-buttonset` CSS and basically build your own wrapper component that knows how to apply the `justify-content:justify` dynamically or has the mutliple rows depending on the browser.  

I am not sure there is anything PrimeReact can actually fix here?

**Comment by airowe** [comment]
@melloware Thanks for the reply. I think I'll build my own with the Prime Faces buttons. Closing now.
