### ISSUE TITLE
Calendar: StepMinute should initialize value

### ISSUE THREAD

**Issue by melloware** [primefaces/primereact#3770]
### Describe the bug

Reported in this comment: https://github.com/primefaces/primereact/issues/2301#issuecomment-1345251962

### Reproducer

https://codesandbox.io/s/withered-cdn-gedup5

### PrimeReact version

8.7.3

### React version

17.x

### Language

TypeScript

### Build / Runtime

Create React App (CRA)

**Comment by melloware** [comment]
cc @MNazakov

**Comment by MNazakov** [comment]
Hi @melloware, thanks for the quick update on this, much appreciated!

I noticed a small issue with the default value in this PR. When the current time is past :30 ( e.g. :35, :41, etc. ) it rounds the default minutes to 60 and it doesn't account for the hour change and minutes reset to :00, so if the current time is for example 12:35, the result will be 12:60 :sweat_smile: I noticed that the logic for that is already present in the _incrementMinute_ function. Maybe we can just call increment/decrement minute functions inside _createMinutePicker_ instead of directly using _doStepMinute_ when stepMinute is > 1

**Comment by melloware** [comment]
Let me take a look.  I do know the hours do not roll when you from 58, 59, 00 it does not roll over to the next hour as this is a minute picker only.

Looks at my PF PR you are right it does it in increment and decrement minute as well.

**Comment by melloware** [comment]
OK I submitted another PR that accounts for minutes > 60 and rolls the hour to the next hour. So at 7:44 it makes it 8:00

**Comment by MNazakov** [comment]
> Let me take a look. I do know the hours do not roll when you from 58, 59, 00 it does not roll over to the next hour as this is a minute picker only.
> 
> Let me do some testing with 12:35

Ah, yes, you are absolutely correct! They should not roll over, my bad!

Thank you

**Comment by melloware** [comment]
I htink on initial display though it should roll over.  Becuase if it is 7:45 and you have step 30 it was making it 7:00 which makes not sense to an end user.  So I like the "principal of least surprise" I would think a user would expect this to start at 8:00.

**Comment by melloware** [comment]
I can also confirm this new behavior is what PrimeFaces JSF was already doing. so this was a good fix

**Comment by MNazakov** [comment]
@melloware yes, it actually makes sense for the roll over on initial value. I thought it was regarding the interaction :sweat_smile: Anyways, thank you for the fix! I am glad to see this issue resolved so quickly, and I'll update our dependencies to 8.7.4 once it releases.

Cheers!
