### ISSUE TITLE
Toast: can't show two toasts in same frame

### ISSUE THREAD

**Issue by inad9300** [primefaces/primereact#3941]
### Describe the bug

Two consecutive calls to `toast.current.show()` result in a single toast being shown. This is possibly the same problem that prevented `clear()` and `show()` to be called consecutively (see https://github.com/primefaces/primereact/issues/2925#issuecomment-1137261071).

The toast API is a little confusing overall, I have to say.

For one, the `<Toast />` component doesn't represent a toast, but rather a set of toasts. Besides the immediate semantic mismatch, this makes it unclear whether one is supposed to have a single `<Toast />` element for the entire application, or rather multiple of them following some elusive criteria. At the same time, this seems to make it impossible to get references to individual toasts, to do things like clearing them selectively.

The other thing I find really difficult to do is triggering toasts from outside a React context. A common thing I like doing is funneling most HTTP error messages through a toast, which I struggle to accomplish with React/PrimeReact (see https://stackoverflow.com/questions/74996068/trigger-toast-from-outside-react-component/75004184).

**Edit:** A quick Google showed this nice-looking library, which could be good inspiration: https://react-hot-toast.com.

> Call it to create a toast from anywhere, even outside React. Make sure you add the [`<Toaster/>`](https://react-hot-toast.com/docs/toaster) component to your app first.

### Reproducer

https://codesandbox.io/s/keen-payne-fgt8ks?file=/src/demo/ToastDemo.js

### PrimeReact version

8.7.3

### React version

18.x

### Language

ALL

### Build / Runtime

Create React App (CRA)

### Steps to reproduce the behavior

1. Click "Show".
2. Observe how only one toast appears, despite the code attempting to show two.
3. Change the call that triggers the second toast to be inside `setTimeout()` with 0 delay. In some less simplified situations, I have found that even this doesn't work, and some arbitrary non-zero delay needs to be introduced.
4. Observe how two toasts appear now after clicking "Show".

**Comment by melloware** [comment]
It would be interesting to study his code and see how he exposes his object outside of React?  I would have to be some JS global right?

**Comment by melloware** [comment]
OK so this makes sense.  

**Issue:** 
When doing this in React...

```js
    const showConcurrent = () => {
        toast.current.show([{ severity: 'success', summary: 'Message 1', detail: 'Message 1 Content', life: 3000 }]);
        toast.current.show([{ severity: 'info', summary: 'Message 2', detail: 'Message 2 Content', life: 3050 }]);
    };
```

**Hack (setTimeout):** 
You are inside of one hook.  So React will not render until the onClick method is left.  And in this case your have replaced the state content of message1 with message2 so that is what renders.

By wrapping in `setTimeout` you are causing the first one to be called and since its done on the background thread React renders and the same for the second call. But as you said you have to tweak the `100 ms` timeout as the CPU might be fast enough to still only render once.

```js
    const showConcurrent = () => {
        setTimeout(() => toast.current.show([{ severity: 'success', summary: 'Message 1', detail: 'Message 1 Content', life: 3000 }]), 0);
        setTimeout(() => toast.current.show([{ severity: 'info', summary: 'Message 2', detail: 'Message 2 Content', life: 3050 }]), 100);
    };
```

This as you know is the nature of React to prevent re-renders whenever possible.  

**Better Hack (flushSync):** 
You can also use `flushSync` in react 18: https://beta.reactjs.org/reference/react-dom/flushSync  Which you don't need to concern yourself with `timeout` as it forces a flush of the rendering before making the next call.

```js
import { flushSync } from 'react-dom';

    const showConcurrent = () => {
        flushSync(() => {
            toast.current.show([{ severity: 'success', summary: 'Message 1', detail: 'Message 1 Content', life: 3000 }]);
        });
        flushSync(() => {
            toast.current.show([{ severity: 'info', summary: 'Message 2', detail: 'Message 2 Content', life: 3050 }]);
        });
    };
```

Not sure there is an easy way to fix this component since its internally using `useState` to handle when the messages change.

**Comment by melloware** [comment]
Added a showcase example so if others have this question in the future.
