### ISSUE TITLE
Cannot destructure property 'setRipple' of '(0 , index_js_.useContext)(...)' as it is undefined.

### ISSUE THREAD

**Issue by RuiBaiXYZ** [primefaces/primereact#4822]
### Describe the bug

TypeError: Cannot destructure property 'setRipple' of '(0 , index_js_.useContext)(...)' as it is undefined.
    at Layout (webpack-internal:///1948:2381:5)
    at renderWithHooks (webpack-internal:///3116:16305:18)
    at mountIndeterminateComponent (webpack-internal:///3116:20069:13)
    at beginWork (webpack-internal:///3116:21582:16)
    at beginWork$1 (webpack-internal:///3116:27421:14)
    at performUnitOfWork (webpack-internal:///3116:26552:12)
    at workLoopSync (webpack-internal:///3116:26461:5)
    at renderRootSync (webpack-internal:///3116:26429:7)
    at recoverFromConcurrentError (webpack-internal:///3116:25845:20)
    at performConcurrentWorkOnRoot (webpack-internal:///3116:25745:22)

### PrimeReact version

9.6.2

### React version

18.x

### Language

TypeScript

### Build / Runtime

Create React App (CRA)

### Browser(s)

Google Chrome 116.0.5845.96

### Steps to reproduce the behavior

Initialize layout

### Expected behavior

Layout normally displayed.

**Comment by melloware** [comment]
You didn't post any code how you are using setRipple?

**Comment by ubau** [comment]
Probably `<PrimeReactProvider>` is missing.

On the other hand the previous (deprecated since v.9.6.0) way `PrimeReact.ripple = true;` is much simpler and easier to use than the new one with `<PrimeReactProvider>` and `PrimeReactContext` and hooks. I think it is a bit of overengineering,  so I would be happy if the deprecation would be removed from previous on and it coud be used as well.

**Comment by ubau** [comment]
Probably <PrimeReactProvider> is missing.

On the other hand the previous (deprecated since v.9.6.0) way PrimeReact.ripple = true; is much simpler and easier to use than the new one with <PrimeReactProvider> and PrimeReactContext and hooks. I think it is a bit of overengineering, so I would be happy if the deprecation would be removed from `PrimeReact` and it coud be used as well.

**Comment by ubau** [comment]
Probably `<PrimeReactProvider>` is missing.

On the other hand the previous (deprecated since v.9.6.0) way `PrimeReact.ripple = true;` is much simpler and easier to use than the new one with `<PrimeReactProvider>` and `PrimeReactContext` and hooks. I think it is a bit of overengineering, so I would be happy if the deprecation would be removed from `PrimeReact` and it coud be used as well.

**Comment by melloware** [comment]
See for proper usage: https://codesandbox.io/s/primereact-demo-forked-r6zksp?file=/src/App.js
