### ISSUE TITLE
docSectionNav: Selected incorrect docNav when page reloaded.

### ISSUE THREAD

**Issue by thejus557** [primefaces/primereact#4924]
### Describe the bug

1. Go this link http://localhost:3000/datatable/#reorder.
2. Refresh the page 1st time. Observe the highlighed docNav.
3. Refresh the page 2nd time. Observe the highlighed docNav.
4. Refresh the page 3rd time. Observe the highlighed docNav.

Each time the highlighed one is different. And the scroll is displaying irrelavant docNav id.

### Reproducer

https://primereact.org/datatable/#reorder

### PrimeReact version

9.4.0

### React version

18.x

### Language

TypeScript

### Build / Runtime

Vite

### Steps to reproduce the behavior

1. Go this link http://localhost:3000/datatable/#reorder.
2. Refresh the page 1st time. Observe the highlighed docNav.
3. Refresh the page 2nd time. Observe the highlighed docNav.
4. Refresh the page 3rd time. Observe the highlighed docNav.

Each time the highlighed one is different. And the scroll is displaying irrelavant docNav id.

### Expected behavior

It should only scroll to hashedItem.
It should only highlight the hashedItem in docNav

**Comment by melloware** [comment]
Agreed and PrimeTek is aware of the issue.

**Comment by ulasturann** [comment]
Thank you for reporting this issue. As @melloware mentioned, we are aware that this issue is occurring due to the presence of numerous rendered datatable demos on a single page. Additionally, because there are so many demos, DocSectionNav is unable to scroll to the active demo's position, resulting in the highlighting of the wrong item.

We will find a solution related to the issue. Thanks again!

**Comment by melloware** [comment]
Looks like it is working in the latest version of the showcase
