### ISSUE TITLE
Button: Invalid button height

### ISSUE THREAD

**Issue by CRC32EX** [primefaces/primereact#5290]
### Describe the bug

English text is no problem. Same height.
```
label="Copy"
```

Japanese text has problem. Height changed.
```
label="コピー"
```
![image](https://github.com/primefaces/primereact/assets/25629617/1bad879a-b0e8-400d-a580-4f5ca2bb96cf)

### Reproducer

https://stackblitz.com/edit/vitejs-vite-gaqhgt?file=src%2FApp.tsx

### PrimeReact version

10.0.9

### React version

18.x

### Language

TypeScript

### Build / Runtime

Vite

### Browser(s)

Chrome Latest(119.0.6045.124)

### Expected behavior

Same height

**Comment by melloware** [comment]
fixed it: https://stackblitz.com/edit/vitejs-vite-upmgvm?file=src%2FApp.tsx,src%2FApp.css,src%2Findex.css,src%2Fmain.tsx

This Stack Overflow explains it: https://stackoverflow.com/questions/59677365/how-to-make-english-text-appear-the-same-size-as-japanese-text

Basically because it was using two different fonts the browser will render two differenet sizes. I simply told PrimeReact to use the same Japanese Font for everyone with..

```css
:root {
  font-family: 'Yu Gothic', sans-serif;
}
```
