### ISSUE TITLE
DataTable: ResizeableColumns doesnt work with unstyled

### ISSUE THREAD

**Issue by GilbertoFreitasJunior997** [primefaces/primereact#5706]
### Describe the bug

When unstyled is set to "true" with Tailwind presets, the "reordarableColumns" doesnt work.

### Reproducer

https://stackblitz.com/edit/bsqxte?file=src%2FApp.jsx

### PrimeReact version

10.3.0

### React version

18.x

### Language

TypeScript

### Build / Runtime

Vite

### Steps to reproduce the behavior

1. Open the stackblitz url
2. Try to resize a column
3.  it will select all text (can be fixed with className="[&>*]:select-none") and wont resize.

**Comment by kl-nevermore** [comment]
@GilbertoFreitasJunior997 
it's seems to only have problems with csb and stackblitz
can not drag with unstyled has been fixed by #5713  and release in 10.3.1
I tested your project in chrome,it's worked
![20240111110153_rec_](https://github.com/primefaces/primereact/assets/25167742/83d05349-a67b-4397-b365-d7bbb5a25f1b)

**Comment by GilbertoFreitasJunior997** [comment]
@kl-nevermore tested again on my project and it works with 10.3.1. thanks!
