### ISSUE TITLE
Calendar: Can't higlight text of underlying input due to focus being lost

### ISSUE THREAD

**Issue by ShaneCallananAerlytix** [primefaces/primereact#5944]
### Describe the bug

It's not possible to highlight/select text in the Calendar input.
This relates to the overlay panel, which when shown causes the input element to lose focus.
When I set `showOnFocus` to `false` the issue disappears

### Reproducer

https://codesandbox.io/p/sandbox/primereact-test-forked-qdhntz

### PrimeReact version

10.2.1

### React version

17.x

### Language

TypeScript

### Build / Runtime

Create React App (CRA)

### Browser(s)

Chrome 121

### Steps to reproduce the behavior

Demonstration 1 (Input Losing Focus):

1. Go to codesandbox provided
2. Click on the Calendar Input
3. Expect input to retain focus

Demonstration 2 (Can't highlight text):
1. Go to codesandbox provided
2. Using the mouse, try to highlight the year portion of the Calendar Input
3. Expect year portion to be highlighted/selected

### Expected behavior

Demonstration 1: Input loses focus after overlay panel is shown
Demonstration 2: Nothing is selected due to input element losing focus (a 2nd attempt to highlight will work)

Demonstration 3 (showOnFocus=false):
1. Go to codesandbox provided
2. Add prop `showOnFocus=false` to `<Calendar>`
3. Try highlighting text now
4. It works!

**Comment by melloware** [comment]
Yes due to ARIA and Accessibility requirements when the popup is displayed it MUST have focus for visually impaired users. You should not be interacting with the text box while the popup is up as you are no longer interacting with the popup.  So `showOnFocus={false}` is the correct way if you do not want the popup grabbing focus.

This is all based on ARIA accessibility requirements.

**Comment by ShaneCallananAerlytix** [comment]
Ok, thanks for the clarification @melloware
