### ISSUE TITLE
TreeTable: sortFunction is not called when custom sort is used

### ISSUE THREAD

**Issue by BAISTM** [primefaces/primereact#6115]
### Describe the bug

The column's custom sort function is not called when sorting a column.

### Reproducer

https://stackblitz.com/edit/vqw5gi-jmmcd5?file=src%2FApp.jsx

### PrimeReact version

10.3.1

### React version

17.x

### Language

TypeScript

### Build / Runtime

Create React App (CRA)

### Expected behavior

The multi sort mode should allow users to customize the sort of a column.

**Comment by melloware** [comment]
Duplicat of: https://github.com/primefaces/primereact/issues/6083 ?

**Comment by MBelniak** [comment]
You need to pass 'custom' as a sortable prop to make it work:
``sortable={'custom'}``
It's working nice on my side. The only problem I had was missing typings, which I created an issue for: https://github.com/primefaces/primereact/issues/5591

BUT
I have a problem, that the custom sort function is not called for the default sorted column. You can use 'sortField' and 'sortOrder' props on DataTable or TreeTable to set the default sorting on column, but the data is sorted using some default algorithm instead of sortFunction. @melloware Maybe it's something that doesn't take much to fix?

**Comment by MBelniak** [comment]
Oh, I see there's been a change recently here https://github.com/primefaces/primereact/blob/master/components/lib/treetable/TreeTable.js#L227 so `sortable={'custom'}` is no longer needed, just `sortable` is enough.

**Comment by melloware** [comment]
@MBelniak so its all working?

**Comment by melloware** [comment]
@MBelniak it looks like @BAISTM Stackblitz above is still not working and he is using `sortable` can you take a look?

**Comment by MBelniak** [comment]
I believe the problem with custom sort function not being called for column with default sorting is still there. I'm checking right now. It might be it's a one liner change with setting a default value for columnField ref

**Comment by MBelniak** [comment]
@melloware  I can confirm that custom sortFunction is not called when sortMode is 'multiple'. The function sortMultipleNodes is called in such case and it does not care about custom sortFunction

**Comment by MBelniak** [comment]
Okay, the fix for default sorting with custom sortFunction will not be so simple. The TreeTableHeader needs to pass info about sortFunction and sortable props of Column to state of TreeTable in order to reference them in onSort. I will investigate further later.

**Comment by MBelniak** [comment]
Turned out to be not so difficult, PR: https://github.com/primefaces/primereact/pull/6436
