### ISSUE TITLE
Checkbox: prop `onClick` changes the event type in 10.5.3

### ISSUE THREAD

**Issue by datacampsis** [primefaces/primereact#6231]
### Describe the bug

In version 10.5.0, the Checkbox's `onClick` event type was CheckboxClickEvent: 
![image](https://github.com/primefaces/primereact/assets/33751140/5c77caaa-1a29-45be-98d2-6233941555c2)

Now is HtmlDivElement, and property `checked` not exists:
![image](https://github.com/primefaces/primereact/assets/33751140/a4778d20-c3d9-4a31-8f03-ad97523d2d25)

### Reproducer

https://stackblitz.com/edit/ovmva7?file=src%2FApp.tsx

### PrimeReact version

10.5.3

### React version

18.x

### Language

TypeScript

### Build / Runtime

Create React App (CRA)

### Expected behavior

Expects the type CheckboxClickEvent and access the `checked` prop

**Comment by melloware** [comment]
Looks like this is a still an issue in 10.6.3

**Comment by melloware** [comment]
@dvpritzbuer interested in helping with this one?  The Checkbox Typescript def is definitely not correct.

**Comment by dvpritzbuer** [comment]
@melloware if it's not super urgent and next week would be fine for the PR I can have a look at it

**Comment by dvpritzbuer** [comment]
@melloware the change was made in #6109 and should be fine

@datacampsis please try `onClick={(e) => e.target.checked}`

**Comment by dvpritzbuer** [comment]
@melloware 
had a deeper look and tried to do the cast for the user so they don't have to do (e.target as HTMLInputElement).checked themself everytime.
The problem is that the underlying react event doesn't pass a generic for target and always sets it to any:
![image](https://github.com/primefaces/primereact/assets/71505298/b9b072d1-51e2-41b4-9c0e-d135a3e67c40)

So the only chance would be to again (after you removed it in #6109) define a custom onClick function that specifically sets the target property correct. You don't need an additional interface for that and could just go with `onClick?(event: React.MouseEvent<HTMLInputElement> & { target: HTMLInputElement }) => void` within the CheckboxProps.

**Comment by dvpritzbuer** [comment]
@melloware 
Tried to find a solution so the user doesn't have to do the cast themself everytime.

The problem is that the underlying react event with target always gets passed EventTarget as target property:
![image](https://github.com/primefaces/primereact/assets/71505298/db9234f1-6422-4a9a-9d41-017fe4f29b5b)
![image](https://github.com/primefaces/primereact/assets/71505298/b4030a32-947f-4901-a04c-355b1adc3320)

So the only solution would be to add a specific definition for the onClick method again. Maybe you don't define an additional interface for that and just extend the CheckboxProps interface with `onClick?: (
    event: React.MouseEvent<HTMLInputElement> & { target: HTMLInputElement }
  ) => void;`

**Comment by melloware** [comment]
@dvpritzbuer can you review my PR I think I got it right?

**Comment by dvpritzbuer** [comment]
@melloware 
yes, approved
