### ISSUE TITLE
Stepper: onChange function doesn't work

### ISSUE THREAD

**Issue by espezaliate** [primefaces/primereact#6475]
### Describe the bug

The onChange function doesn't do anything. Also would be nice to have access to total steps and maybe last, previous, next.

### Reproducer

https://stackblitz.com/edit/rp5vx5?file=src%2FApp.tsx

### PrimeReact version

10.6.3

### React version

17.x

### Language

TypeScript

### Build / Runtime

Create React App (CRA)

**Comment by Rekl0w** [comment]
In the code, buttons manually controlling the navigation between steps using the `nextCallback` and `prevCallback` methods. These methods do not trigger the `onChange` event.

If you want to execute some code when the step changes, you could do this within the `onClick` handlers of your "Next" and "Back" buttons. 

`
<Button
  label="Next"
  icon="pi pi-arrow-right"
  iconPos="right"
  onClick={() => {
    stepperRef.current.nextCallback();
    console.log('Step changed to: ' + (stepperRef.current.state.activeIndex + 1));
  }}
/>
`

**Comment by espezaliate** [comment]
I'm referencing this part of the documentation of the stepper component:
![Stepper API](https://github.com/primefaces/primereact/assets/88797963/21ccc623-2559-4058-a3cc-6248e3f1f3ba)

**Comment by espezaliate** [comment]
> In the code, buttons manually controlling the navigation between steps using the `nextCallback` and `prevCallback` methods. These methods do not trigger the `onChange` event.
> 
> If you want to execute some code when the step changes, you could do this within the `onClick` handlers of your "Next" and "Back" buttons.
> 
> `<Button label="Next" icon="pi pi-arrow-right" iconPos="right" onClick={() => { stepperRef.current.nextCallback(); console.log('Step changed to: ' + (stepperRef.current.state.activeIndex + 1)); }} />`

also, I'm unable to access state through the ref, the only available functions it reveals are next previous and get element

**Comment by melloware** [comment]
Submitted a PR to add `getActiveStep()` and `setActiveStep(step)` to the `ref`.

**Comment by ivaneliasoo** [comment]
Hi, I'm facing this issue too, and I believe that problem is the event name so it must be wrong in [documentation ("onChange") ](https://primereact.org/stepper/#api.Stepper.callbacks.onChange) or in [code ("onChangeStep") ](https://github.com/primefaces/primereact/blob/38b891c00d7ce21a42067814ed0a3d15bd25b558/components/lib/stepper/Stepper.js#L52), so using "onChangeStep" works correctly  but with type errors
![image](https://github.com/primefaces/primereact/assets/3597021/79282dfd-b910-4d30-a522-b2769dc60258)
but no event info is returned, only index info 
![image](https://github.com/primefaces/primereact/assets/3597021/242c79be-5cb6-4373-ac7b-3c0eb277f20f)

**Comment by melloware** [comment]
@ivaneliasoo I just fixed it for next release: https://github.com/primefaces/primereact/pull/6546

**Comment by rahulAnand1999** [comment]
how to stop navigation from the header

**Comment by Vickyvignesh-01** [comment]
> how to stop navigation from the header [@Rekl0w](https://github.com/Rekl0w)

have u found that?
