### ISSUE TITLE
DataTable: Global filter resets column filters

### ISSUE THREAD

**Issue by Matthew404-fail** [primefaces/primereact#6663]
### Describe the bug

The global filter resets column filters.

### Reproducer

https://stackblitz.com/edit/jyzjs8?file=src%2FApp.tsx

### PrimeReact version

10.6.5

### React version

18.x

### Language

TypeScript

### Build / Runtime

Create React App (CRA)

### Steps to reproduce the behavior

1. Go to reproducer
2. Apply any column filter
3. Enter any text in global filter field
4. Column filter has been reset
5. If you enter "Amy" in global filter field and then apply a column filter, it will work correctly![image](https://github.com/primefaces/primereact/assets/66127533/af42b9e0-ab30-4705-8794-0d20319fd6b7)
![image](https://github.com/primefaces/primereact/assets/66127533/fc713114-5041-4889-8c77-19cea61ef5fb)
![image](https://github.com/primefaces/primereact/assets/66127533/ff745d73-2cc6-454a-94a2-cde95b75761c)

### Expected behavior

Filters will be applied together

**Comment by Et7f3** [comment]
I can reproduce your error even with recent 10.8.0 version.
I think you just have too much code:
https://stackblitz.com/edit/vzt525-cyndyh?file=src%2FApp.jsx here it is a less buggy version: You can add column filter before global filter or the opposite and they will combine.
Try with o in global filter and "Bl" start with in name. You will see they merge correctly.

I said less buggy because when you erase global filter you get no filter (you need to reapply them) but this might be a desired behavior.

**Comment by melloware** [comment]
@Et7f3 so is this not a bug?

**Comment by Et7f3** [comment]
@Matthew404-fail 
your filter state is updated with your global handler and also by column event (when you click apply).

So in your reproducer I added line 431:
```
onFilter={(e) => setFilters(e.filters)}
```

and I wasn't able to reproduce the issue. You could also update with `onFilterApplyClick` on `Column` if you want to be more precise.

@melloware it is a documentation bug. The [example given](https://primereact.org/datatable/#advanced_filter) doesn't update the filter object. The reproducer was mostly taken for this example.

I proposed this PR https://github.com/primefaces/primereact/pull/6974
