### ISSUE TITLE
Carousel: does not cycle circular when onPageChange assigned

### ISSUE THREAD

**Issue by sancelot** [primefaces/primereact#6701]
### Describe the bug

carousel does not cycle circular, when onPageChange event is assigned and circular is true 

### Reproducer

https://stackblitz.com/edit/vitejs-vite-w3cabn

### PrimeReact version

^10.6.6

### React version

18.x

### Language

TypeScript

### Build / Runtime

Vite

### Browser(s)

edge

### Steps to reproduce the behavior

click on right button to cycle through pages

### Expected behavior

should cycle circular

**Comment by KirilCycle** [comment]
@melloware I assume the ‘onPageChange’ method is added to allow the user to manually control the carousel along with the ‘page’ prop ?

**Comment by melloware** [comment]
@KirilCycle yes it is.

**Comment by felipefranca** [comment]
If you remove onPageChange={onChange} then the page control will work due to the fact that the page change is done by the component itself.
If you provide an onPageChange property, you need to provide a page and control page changes manually.
That's why it's not working, you're providing an onPageChange without treating the pages correctly.

**Comment by melloware** [comment]
@felipefranca so this is "As designed" correct?

**Comment by sancelot** [comment]
I was thinking that was a callback that will permit to notify that page has changed .

**Comment by felipefranca** [comment]
@melloware Yes, it was designed in this way, to work well you need to call onChange to complete the operation
@sancelot Yes too, but you need to call the onChange after to change the page number to complete the operation
