### ISSUE TITLE
ConfirmDialog: 'group' does not exist in type 'ConfirmDialogProps'

### ISSUE THREAD

**Issue by abdullahnazzal** [primefaces/primereact#6855]
### Describe the bug

Issue 1: 
Object literal may only specify known properties, and 'group' does not exist in type 'ConfirmDialogProps'.

```js
confirmDialog({
            group: 'templating',
            header: 'Confirmation',
            message: (
                <div className="flex flex-column align-items-center w-full gap-3 border-bottom-1 surface-border">
                    <i className="pi pi-exclamation-circle text-6xl text-primary-500"></i>
                    <span>Please confirm to proceed moving forward.</span>
                </div>
            ),
            accept,
            reject
        });
```
        
Issue 2: 

No overload matches this call.
  Overload 1 of 2, '(props: ConfirmDialogProps): ConfirmDialog', gave the following error.
    Type '{ group: string; }' is not assignable to type 'IntrinsicAttributes & IntrinsicClassAttributes<ConfirmDialog> & Readonly<ConfirmDialogProps>'.
      Property 'group' does not exist on type 'IntrinsicAttributes & IntrinsicClassAttributes<ConfirmDialog> & Readonly<ConfirmDialogProps>'.
  Overload 2 of 2, '(props: ConfirmDialogProps, context: any): ConfirmDialog', gave the following error.
    Type '{ group: string; }' is not assignable to type 'IntrinsicAttributes & IntrinsicClassAttributes<ConfirmDialog> & Readonly<ConfirmDialogProps>'.
      Property 'group' does not exist on type 'IntrinsicAttributes & IntrinsicClassAttributes<ConfirmDialog> & Readonly<ConfirmDialogProps>'.
      
      <ConfirmDialogPrime group="templating"  />
      

### PrimeReact version

^10.6.5

### React version

18.x

### Language

TypeScript

### Build / Runtime

Create React App (CRA)

**Comment by melloware** [comment]
@abdullahnazzal what makes you think there is a `group` property its not listed here: https://primereact.org/confirmdialog/#api.ConfirmDialog.props

**Comment by Mirkesx** [comment]
Sorry for posting on a closed issue, I had the same problem that @abdullahnazzal and I just want to point out one thing, which is probably the real problem here.

@melloware you are correctly pointing out that the props section doesn't list the "group" property, but if you have a look at the documentation it is litterally showing examples of the "group" prop everywhere:
- https://primereact.org/confirmdialog/#declarative
- https://primereact.org/confirmdialog/#template
- https://primereact.org/confirmdialog/#responsive
- https://primereact.org/confirmdialog/#headless

I have one question: is a documentation error or is it a future feature not implemented yet/breaking change from past versions?

Since someone put lot of effort to write that documentation listing the "group" prop, it is either a bug/future feature or it is a copy-paste went wrong from the documentation of another primeface related project. 

Either way, the documentation should be fixed, or it should be implemented/restored the support to the "group" prop.

If it is a bug in the documentation of ConfirmDialog, I'd suggest to go through the examples very thoroughly as it seems the examples  in the "feature" section are not consistent at all with the list of supported props in the "prop" section: not only they are showing usage of "group", but they also show usage of the "trigger" prop (which is not listed in the "prop" section). Also, the documentation fails in explaining what is the structure of the "configuration object for customization" passed to the "confirmDialog" method, and what are the differences with the list of props the ConfirmDialog components supports.

**Comment by melloware** [comment]
let me look through the commits.  I see what you are saying now. I will reopen and investigate.

**Comment by melloware** [comment]
PR submitted the Typescript was missing!
