### ISSUE TITLE
InputNumber: Buttons do not show correctly

### ISSUE THREAD

**Issue by nicholas-brooks** [primefaces/primereact#6953]
### Describe the bug

When `showButtons` is true, the buttons on the right of the input, do **NOT** show correctly - that is, instead of the up button showing above the down button (and both being half-height of the input field), they are showing next to each other as full-height buttons.

Have a look at https://v9.primereact.org/inputnumber/#buttons for how the buttons should display.

Note: The issue also exists when the `buttonLayout` is set to `vertical`.

### Reproducer

https://stackblitz.com/edit/vitejs-vite-k36hgk?file=src%2FApp.tsx

### System Information

primereact: v10.8.0

### Steps to reproduce the behavior

1. Add InputNumber
2. Set showButtons to true

### Expected behavior

Buttons should be showing as at https://v9.primereact.org/inputnumber/#buttons.

**Comment by redonearth** [comment]
It looks like a typo in the text above.
do `now` show correctly 👉🏻 do `not` show correctly

**Comment by marilliguicota** [comment]
This bug is also visible in the current documentation: https://primereact.org/inputnumber/#buttons

<img width="1121" alt="Version 9" src="https://github.com/user-attachments/assets/1488291e-3dbe-446c-8a47-3c4c6ac03a67">
<img width="1049" alt="Version 10" src="https://github.com/user-attachments/assets/6ba91cf0-5dab-4c9f-a367-1cceca66433f">

Screenshots taken on Chrome 125.0.6422.78 on OSX.
