### ISSUE TITLE
Error NAN/NAN/NAN 

### ISSUE THREAD

**Issue by JOSE89** [primefaces/primereact#707]
**I'm submitting a 
```
[*] bug report
[ ] feature request
[ ] support request => Please do not submit support request here, instead see https://forum.primefaces.org/viewforum.php?f=57
```

**Plunkr Case (Bug Reports)**

https://plnkr.co/edit/OHj3gZZmFmgVQl6Z2eql?p=preview

**Current behavior**
When you enter a wrong date with a keyboard, when executing the onChane event, it appears in the NAN / NAN / NAN / component

**Expected behavior**
The component should have a mask that only allows valid dates to be entered from the keyboard.

**Minimal reproduction of the problem with instructions**
Write in the component 'string'. 
This 'string' put in onChange. new Date ('string');

**Please tell us about your environment:**
Windows 10. 
Visual Studio Code

* **React version:**
 "react": "^16.4.0",

* **PrimeReact version:**
"primereact": "^2.0.1",

* **Browser:** [all | Chrome XX | Firefox XX | IE XX | Safari XX | Mobile Chrome XX | Android X.X Web Browser | iOS XX Safari | iOS XX UIWebView | iOS XX WKWebView ]

 
* **Language:** [all | TypeScript X.X | ES6/7 | ES5]

**Comment by JOSE89** [comment]
@vnallamhawk yes

**Comment by cagataycivici** [comment]
I'm unable to replicate, the component does not guarantee that you'll get a date, similar to input fields, it passes what has been typed or selected. If selected, it is date for sure but when being typed, it can be a date or a string so that you can handle further logic on your side. In your case, you don't need to parse to date manually or if you do, make sure you check for parse errors. Calendar components parses the input itself, if it is a valid date onchange event gets a Date, if not it gets a string.
