### ISSUE TITLE
PrimeReactProvider: cssTransition false does not disable animations globally

### ISSUE THREAD

**Issue by elburro1887** [primefaces/primereact#7395]
### Describe the bug

When setting `cssTransition` to `false` in `PrimeReactProvider`, animations are not disabled globally:

````
<PrimeReactProvider value={{ cssTransition: false }}>
    <App />
</PrimeReactProvider>
````

Setting `transitionOptions={{ disabled: true }}` on the Component itself works though.

### Reproducer

https://stackblitz.com/edit/cc98j5-u72fsi?file=src%2FApp.jsx

### System Information

```Shell
...
```

### Steps to reproduce the behavior

`<PrimeReactProvider value={{ cssTransition: false }}>`

### Expected behavior

Disabled animations on a global level

**Comment by tneeraja95** [comment]
Had a look at the code and found the bug - 
Problem is in file `PrimeReactContext.js`, line 15

 `const [cssTransition, setCssTransition] = useState(propsValue.cssTransition || true);`

|| is OR, which basically means that even when cssTransition from props is `false`, `false || true `return `true`.

Instead of OR what we really want is 'Nullish coalescing operator (??)', which returns its right-hand side operand when its left-hand side operand is [null](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Operators/null) or [undefined](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/undefined), and otherwise returns its left-hand side.

I think, we should replace || with ?? for other props as well.

Have created this PR in my local fork - https://github.com/primefaces/primereact/pull/7417

Please have a look and give me permission to make this change.

**Comment by melloware** [comment]
Yes please make the changes to the other props as well.
