### ISSUE TITLE
Keyboard accessibility for Calendar

### ISSUE THREAD

**Issue by emiravete** [primefaces/primereact#885]
Instantiate a [Calendar](https://www.primefaces.org/primereact/#/calendar) object in your react code.
Try to select a date only by using the keyboard.
You cannot do that.

Version: 3.1.1

**Comment by BuckAMayzing** [comment]
@emiravete  - you can do this now, although there is a bit of extra work to be done. Your onChange function needs to treat the event argument's value property as a string, and only parse to a date if it is a valid date. I used moment for this validation. I'm using typescript, so I did have to expand the type for the value to include strings instead of just Date | Date[] as the event value is defined today.

That said, adding official support for this would prevent a bunch of code duplication.

**Comment by mertsincan** [comment]
Hi,

Please try TAB and Arrow Keys combinations with the latest version. https://primefaces.org/primereact/showcase/#/calendar

Also, we'll add an accessibility section to the doc pages of all components.

Best Regards,

**Comment by emiravete** [comment]
@mertsincan okay now it works to edit a date with the keyboard. But we still cannot edit a Date/Time only with the keyboard. 
reproduce: 
- goto https://primefaces.org/primereact/showcase/#/calendar
- click on Time / 24h field
- Try to change the time. You can set the focus on the arrow up and down but when you type enter or space nothing to happen. It works only with the mouse.

Can you reopen the issue of I shall to create a new one?

Best regards
